name: Publish packages

on:
  push:
    tags:
      - '**'

jobs:
  publish-nuget:
    if: ${{ startsWith(github.ref, 'refs/tags/dotnet/') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dotnet
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build /warnaserror -c Release
      - name: Push to nuget.org
        run: dotnet nuget push ./Multiflag/bin/Release/Multiflag.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
          
  publish-npm:
    if: ${{ startsWith(github.ref, 'refs/tags/node/') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
